[tool.poetry]
name = "bioinfo-course"
version = "0.1.0"
description = ""
authors = ["Yuchen Xiang"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
scanpy = "^1.9.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
